services:
  - type: web
    name: hakimkononi
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate"
    startCommand: "gunicorn sheria_ai.wsgi:application --bind 0.0.0.0:$PORT --workers 1 --timeout 120"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: META_WHATSAPP_TOKEN
        sync: false
      - key: META_PHONE_NUMBER_ID
        sync: false
      - key: META_VERIFY_TOKEN
        value: hakimkononi2026
      - key: GEMINI_API_KEY
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
