# Generated by Django 5.1.4 on 2026-09-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('section', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('simple_swahili', models.TextField(blank=True)),
                ('related_to', models.CharField(blank=True, max_length=300)),
                ('category', models.CharField(choices=[('constitution', 'Constitution of Kenya 2010'), ('employment', 'Employment'), ('landlord_tenant', 'Landlord & Tenant'), ('criminal_procedure', 'Criminal Procedure'), ('children', 'Children & Family'), ('consumer', 'Consumer Protection'), ('fraud', 'Fraud & Cybercrime'), ('land', 'Land & Succession'), ('other', 'Other')], default='other', max_length=50)),
                ('source_url', models.URLField(max_length=500)),
                ('embedding_json', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Law Section',
                'verbose_name_plural': 'Law Sections',
                'ordering': ['title', 'section'],
            },
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(blank=True, max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('story', models.TextField()),
                ('answer_law', models.TextField(blank=True)),
                ('answer_simple', models.TextField(blank=True)),
                ('answer_loophole', models.TextField(blank=True)),
                ('answer_letter', models.TextField(blank=True)),
                ('raw_answer', models.TextField(blank=True)),
                ('was_helpful', models.BooleanField(blank=True, choices=[(True, 'Ndio — Ilisaidia'), (False, 'Hapana — Haikuwa Sahihi')], null=True)),
                ('what_actually_happened', models.TextField(blank=True)),
                ('correct_section', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('laws_used', models.ManyToManyField(blank=True, to='cases.law')),
            ],
            options={
                'verbose_name': 'User Query',
                'verbose_name_plural': 'User Queries',
                'ordering': ['-created_at'],
            },
        ),
    ]
