# Generated by Django 5.1.4 on 2026-09-16 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.TextField()),
                ('county', models.CharField(blank=True, max_length=100)),
                ('lang', models.CharField(default='sw', max_length=10)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('answer_law', models.TextField(blank=True)),
                ('answer_simple', models.TextField(blank=True)),
                ('answer_loophole', models.TextField(blank=True)),
                ('answer_letter', models.TextField(blank=True)),
                ('is_serious', models.BooleanField(default=False)),
                ('sources_json', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('query', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.query')),
            ],
            options={
                'verbose_name': 'Answer Job',
                'verbose_name_plural': 'Answer Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
