# Generated by Django 5.1.4 on 2026-09-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_answerjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, unique=True)),
                ('lang', models.CharField(choices=[('sw', 'Kiswahili'), ('en', 'English'), ('sheng', 'Sheng')], default='sw', max_length=10)),
                ('state', models.CharField(choices=[('new', 'New — awaiting language choice'), ('active', 'Active')], default='new', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp User',
                'verbose_name_plural': 'WhatsApp Users',
            },
        ),
    ]
