# Generated by Django 5.1.4 on 2026-09-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_whatsappuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlangKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(help_text='The slang/vernacular word or phrase (lowercase)', max_length=100, unique=True)),
                ('topic', models.CharField(choices=[('employment', 'Employment / Job'), ('criminal', 'Criminal / Police / Arrest'), ('land', 'Land / Landlord / Tenant'), ('family', 'Family / Marriage / Divorce')], help_text='Which legal topic this word signals', max_length=30)),
                ('language', models.CharField(choices=[('sheng', 'Sheng'), ('sw', 'Kiswahili'), ('en', 'English'), ('any', 'Any language')], default='any', help_text='Which language this word belongs to', max_length=10)),
                ('notes', models.CharField(blank=True, help_text="Optional note e.g. 'Swahili for police officer'", max_length=200)),
                ('active', models.BooleanField(default=True, help_text='Uncheck to disable without deleting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Slang Keyword',
                'verbose_name_plural': 'Slang Keywords',
                'ordering': ['topic', 'word'],
            },
        ),
    ]
