# Generated by Django 5.1.4 on 2026-09-28 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_slangkeyword'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappuser',
            name='lang',
            field=models.CharField(choices=[('sw', 'Kiswahili'), ('en', 'English'), ('any', 'Any language')], default='sw', max_length=10),
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(help_text='Format: +254XXXXXXXXX', max_length=20)),
                ('whatsapp', models.CharField(blank=True, help_text='WhatsApp number — clients will be connected here. Format: +254XXXXXXXXX', max_length=20)),
                ('national_id_number', models.CharField(blank=True, max_length=30)),
                ('lsk_number', models.CharField(help_text='Format: P.XXX/XXXX/YYYY e.g. P.105/1234/2024', max_length=50, unique=True)),
                ('lsk_name', models.CharField(blank=True, help_text='Full name exactly as it appears on kenyalaw.org LSK register', max_length=200)),
                ('county', models.CharField(help_text='Primary county of practice', max_length=100)),
                ('county_secondary', models.CharField(blank=True, help_text='Second county (optional)', max_length=100)),
                ('specialties', models.JSONField(default=list, help_text="List of specialty codes e.g. ['employment','land']")),
                ('years_experience', models.PositiveSmallIntegerField(default=0)),
                ('firm_name', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True, help_text='Brief professional bio (max 500 chars)', max_length=500)),
                ('doc_practicing_cert', models.FileField(blank=True, help_text='2026 LSK Practicing Certificate (PDF or image)', null=True, upload_to='kyc/certs/')),
                ('doc_national_id', models.FileField(blank=True, help_text='National ID or Passport (front photo)', null=True, upload_to='kyc/ids/')),
                ('doc_selfie_with_id', models.FileField(blank=True, help_text='Selfie holding National ID', null=True, upload_to='kyc/selfies/')),
                ('doc_kra_pin', models.FileField(blank=True, help_text='KRA PIN Certificate', null=True, upload_to='kyc/kra/')),
                ('doc_video', models.FileField(blank=True, help_text="Optional: short video stating name, LSK number, today's date while holding certificate", null=True, upload_to='kyc/videos/')),
                ('profile_photo', models.FileField(blank=True, null=True, upload_to='lawyers/photos/')),
                ('kyc_status', models.CharField(choices=[('pending', 'Pending — Level 1'), ('level1_pass', 'Level 1 Passed — Awaiting Documents'), ('docs_submitted', 'Documents Submitted — Under Review'), ('verified', '✅ Verified'), ('rejected', '❌ Rejected'), ('suspended', '⚠️ Suspended')], default='pending', max_length=20)),
                ('kyc_rejection_reason', models.TextField(blank=True, help_text='Reason sent to lawyer when rejected')),
                ('kyc_notes', models.TextField(blank=True, help_text='Internal admin notes — not shown to lawyer')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide from platform without deleting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_lawyers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lawyer',
                'verbose_name_plural': 'Lawyers',
                'ordering': ['-verified_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone', models.CharField(blank=True, help_text="Wanjiku's phone — only stored if she consented", max_length=20)),
                ('user_consented', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New — not yet contacted'), ('contacted', 'Lawyer contacted client'), ('closed', 'Closed')], default='new', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='cases.lawyer')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='cases.query')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
