# Generated by Django 5.1.4 on 2026-09-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_alter_whatsappuser_lang_lawyer_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='law',
            name='section',
            field=models.CharField(max_length=500),
        ),
    ]
