# Generated by Django 5.1.4 on 2026-10-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='answerjob',
            name='answerjob_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='answerjob',
            name='answerjob_id_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='law',
            name='law_category_idx',
        ),
        migrations.RemoveIndex(
            model_name='whatsappuser',
            name='whatsappuser_phone_idx',
        ),
        migrations.AddField(
            model_name='lawyer',
            name='telegram_username',
            field=models.CharField(blank=True, help_text='Telegram username without @ e.g. JohnAdvocate — clients can reach you here too', max_length=100),
        ),
    ]
