# Generated by Django 5.1.4 on 2026-10-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_add_lawyer_telegram_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='password_hash',
            field=models.CharField(blank=True, help_text='Set by the lawyer via /lawyers/set-password/. Never shown in admin.', max_length=255),
        ),
    ]
