# Generated by Django 5.1.4 on 2026-10-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_lawyer_last_login_at_lawyer_password_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='profile_photo_url',
            field=models.URLField(blank=True, help_text='Direct URL to profile photo (e.g. LinkedIn photo). Optional.', max_length=500),
        ),
    ]
