# Generated by Django 5.1.4 on 2026-10-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_add_lawyer_profile_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerjob',
            name='answer_court_doc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='answerjob',
            name='answer_evidence',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='answerjob',
            name='answer_procedure',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='answerjob',
            name='self_rep',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='query',
            name='answer_court_doc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='query',
            name='answer_evidence',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='query',
            name='answer_procedure',
            field=models.TextField(blank=True),
        ),
    ]
