# Generated by Django 5.1.4 on 2026-10-09 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_add_self_rep_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(help_text='Audio recording of the court hearing (mp3/m4a/wav/ogg, max 25MB)', upload_to='case_audio/')),
                ('lang', models.CharField(default='sw', max_length=10)),
                ('court_station', models.CharField(blank=True, help_text='e.g. Kisumu Magistrate Court', max_length=200)),
                ('hearing_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending transcription'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=10)),
                ('transcript', models.TextField(blank=True, help_text='Raw Whisper transcript')),
                ('summary', models.TextField(blank=True, help_text='AI-generated Swahili summary')),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Case Audio',
                'verbose_name_plural': 'Case Audio Files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='First name or pseudonym — no last name needed', max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('case_type', models.CharField(blank=True, help_text='e.g. Employment, Landlord, Police', max_length=100)),
                ('story', models.TextField(help_text='What happened and how HakiMkononi helped — in their own words')),
                ('outcome', models.CharField(blank=True, help_text="e.g. 'Got 3 months salary back', 'Landlord returned my deposit'", max_length=200)),
                ('lang', models.CharField(default='sw', max_length=10)),
                ('approved', models.BooleanField(default=False, help_text='Check to show publicly on the site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LawyerPublicAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='The legal question being answered (Swahili or English)', max_length=500)),
                ('answer', models.TextField(help_text="The lawyer's answer — max 800 chars, plain language")),
                ('lang', models.CharField(default='sw', max_length=10)),
                ('approved', models.BooleanField(default=False, help_text="Admin must approve before this appears on the lawyer's profile")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_answers', to='cases.lawyer')),
            ],
            options={
                'verbose_name': 'Lawyer Public Answer',
                'verbose_name_plural': 'Lawyer Public Answers',
                'ordering': ['-created_at'],
            },
        ),
    ]
