# Generated by Django 5.1.4 on 2026-10-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_add_caseaudio_testimonial_lawyerpublicanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='pro_bono',
            field=models.BooleanField(default=False, help_text='Check if this lawyer takes pro bono cases — shown in the directory'),
        ),
    ]
