# Generated by Django 5.1.4 on 2026-10-09 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_add_lawyer_pro_bono'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1–5 star rating from Wanjiku after contacting the lawyer', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='rating_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='rating_text',
            field=models.TextField(blank=True, help_text='Optional comment from Wanjiku about the lawyer'),
        ),
        migrations.AddField(
            model_name='lead',
            name='report_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='report_reason',
            field=models.TextField(blank=True, help_text='What Wanjiku reported about this lawyer'),
        ),
        migrations.AddField(
            model_name='lead',
            name='reported',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LawyerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text="What happened — in Wanjiku's own words")),
                ('contact_info', models.CharField(blank=True, help_text='Phone or email if they want us to follow up (optional)', max_length=100)),
                ('reviewed', models.BooleanField(default=False)),
                ('action_taken', models.TextField(blank=True, help_text='What admin did in response (internal)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='cases.lawyer')),
                ('lead', models.ForeignKey(blank=True, help_text='The lead this report is about, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.lead')),
            ],
            options={
                'verbose_name': 'Lawyer Report',
                'verbose_name_plural': 'Lawyer Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
